# Generated by Django 5.2.8 on 2025-11-29 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mission_type', models.CharField(max_length=50)),
                ('planets_visited', models.JSONField()),
                ('resources_collected', models.JSONField()),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_missions', models.IntegerField(default=0)),
                ('total_won', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bet', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planets_discovered', models.IntegerField(default=0)),
                ('total_resources', models.IntegerField(default=0)),
                ('highest_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mining_missions', models.IntegerField(default=0)),
                ('exploration_missions', models.IntegerField(default=0)),
                ('rescue_missions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
