# Generated by Django 5.2.8 on 2025-12-30 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guessinggame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='guessinggame',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='guessingstats',
            name='highest_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='guessingstats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='guessinggame',
            index=models.Index(fields=['user', 'created_at'], name='guessing_gu_user_id_721525_idx'),
        ),
        migrations.AddIndex(
            model_name='guessinggame',
            index=models.Index(fields=['status'], name='guessing_gu_status_e3c35a_idx'),
        ),
    ]
