# Generated by Django 5.2.8 on 2025-12-30 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pyramidexploration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pyramidexploration',
            name='survival_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pyramidexploration',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pyramidstats',
            name='highest_survival_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pyramidstats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='pyramidexploration',
            index=models.Index(fields=['user', 'created_at'], name='pyramid_pyr_user_id_8d3fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='pyramidexploration',
            index=models.Index(fields=['win_ratio'], name='pyramid_pyr_win_rat_e0cfe3_idx'),
        ),
    ]
