# Generated by Django 5.2.8 on 2026-01-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyramid', '0002_alter_pyramidexploration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyramidstats',
            name='divine_artifacts_found',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
