# Generated by Django 5.2.8 on 2025-12-30 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towergame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='towergame',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='towerstats',
            name='highest_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='towerstats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='towergame',
            index=models.Index(fields=['user', 'created_at'], name='tower_tower_user_id_d8959c_idx'),
        ),
        migrations.AddIndex(
            model_name='towergame',
            index=models.Index(fields=['status'], name='tower_tower_status_d0947f_idx'),
        ),
    ]
