# Generated by Django 5.2.8 on 2025-12-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_seed', models.CharField(max_length=128)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('client_seed', models.CharField(max_length=64)),
                ('nonce', models.PositiveBigIntegerField()),
                ('crash_point', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Bets'), ('RUNNING', 'Running'), ('CRASHED', 'Crashed'), ('SETTLED', 'Settled')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('crashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bet_per_player', models.DecimalField(decimal_places=2, default=1000, max_digits=18)),
                ('max_exposure_per_round', models.DecimalField(decimal_places=2, default=10000, max_digits=18)),
                ('max_multiplier_cap', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('allow_demo', models.BooleanField(default=True)),
                ('allow_real_money', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BET_PLACED', 'Bet placed'), ('CASHOUT', 'Cashout'), ('ADMIN_ADJUST', 'Admin wallet adjust'), ('BAN', 'Player banned')], max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'created_at'], name='crash_audit_action_afa507_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrashBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('auto_cashout', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cashed_out_at', models.DateTimeField(blank=True, null=True)),
                ('cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CASHED_OUT', 'Cashed Out'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('is_demo', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='crash.gameround')),
            ],
            options={
                'indexes': [models.Index(fields=['round', 'status'], name='crash_crash_round_i_b13e6f_idx'), models.Index(fields=['user', 'created_at'], name='crash_crash_user_id_7ae53b_idx')],
                'unique_together': {('user', 'round', 'is_demo')},
            },
        ),
    ]
