# Generated by Django 5.2.8 on 2025-12-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risksettings',
            options={'verbose_name': 'Risk Settings', 'verbose_name_plural': 'Risk Settings'},
        ),
        migrations.AddField(
            model_name='risksettings',
            name='bet_cooldown_seconds',
            field=models.IntegerField(default=1, verbose_name='Bet cooldown in seconds'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='max_auto_cashout',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8, verbose_name='Maximum auto cashout multiplier'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='max_bet_per_player_per_round',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=18, verbose_name='Maximum bet per player per round'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='max_bets_per_minute',
            field=models.IntegerField(default=30, verbose_name='Maximum bets per minute'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='max_win_per_bet',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=18, verbose_name='Maximum win per bet'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='min_auto_cashout',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=8, verbose_name='Minimum auto cashout multiplier'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='min_bet_per_player',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=18, verbose_name='Minimum bet per player'),
        ),
        migrations.AlterField(
            model_name='risksettings',
            name='house_edge_percent',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='House edge percentage'),
        ),
        migrations.AlterField(
            model_name='risksettings',
            name='max_bet_per_player',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=18, verbose_name='Maximum bet per player'),
        ),
        migrations.AlterField(
            model_name='risksettings',
            name='max_exposure_per_round',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=18, verbose_name='Maximum exposure per round'),
        ),
        migrations.AlterField(
            model_name='risksettings',
            name='max_multiplier_cap',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8, verbose_name='Maximum multiplier cap'),
        ),
    ]
