# Generated by Django 5.2.8 on 2025-11-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('open_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('starting', 'Starting'), ('running', 'Running'), ('crashed', 'Crashed')], default='waiting', max_length=20)),
                ('crash_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
