# Generated by Django 5.2.8 on 2025-12-01 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0002_crashcandle_livegame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrashCandle',
        ),
        migrations.DeleteModel(
            name='LiveGame',
        ),
        migrations.AlterModelOptions(
            name='crashgame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='crashgame',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
