# Generated by Django 4.2.27 on 2026-01-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0002_alter_risksettings_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crashbet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='crashbet',
            name='is_demo',
        ),
    ]
