# Generated by Django 4.2.27 on 2026-01-26 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crash', '0003_alter_crashbet_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashbet',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='crashbet',
            unique_together={('user', 'round', 'is_demo')},
        ),
    ]
