# Generated by Django 5.2.8 on 2025-12-01 00:55

import crash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0003_delete_crashcandle_delete_livegame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashgame',
            name='id',
            field=models.CharField(default=crash.models.generate_game_id, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
