# Generated by Django 4.2.27 on 2026-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0004_crashbet_is_demo_alter_crashbet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksettings',
            name='max_bet_per_player',
            field=models.DecimalField(decimal_places=2, default=999999999, max_digits=18, verbose_name='Maximum bet per player'),
        ),
    ]
