# Generated by Django 4.2.27 on 2026-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0005_alter_risksettings_max_bet_per_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksettings',
            name='max_bet_per_player_per_round',
            field=models.DecimalField(decimal_places=2, default=999999999, max_digits=18, verbose_name='Maximum bet per player per round'),
        ),
        migrations.AlterField(
            model_name='risksettings',
            name='max_exposure_per_round',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=18, verbose_name='Maximum exposure per round'),
        ),
    ]
