# Generated by Django 5.2.8 on 2025-12-30 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasurehunt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='treasurehunt',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='treasurestats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='treasurehunt',
            index=models.Index(fields=['user', 'created_at'], name='treasure_tr_user_id_2160d8_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurehunt',
            index=models.Index(fields=['win_ratio'], name='treasure_tr_win_rat_66e156_idx'),
        ),
    ]
