# Generated by Django 5.2.8 on 2025-12-30 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minesweepergame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='minesweepergame',
            name='mines_positions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='minesweepergame',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='minesweeperstats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='minesweepergame',
            index=models.Index(fields=['user', 'created_at'], name='minesweeper_user_id_aa1b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='minesweepergame',
            index=models.Index(fields=['status'], name='minesweeper_status_fa8fce_idx'),
        ),
    ]
