# Generated by Django 5.2.8 on 2025-11-30 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotstats',
            options={'verbose_name_plural': 'Slot Statistics'},
        ),
        migrations.AddField(
            model_name='slotstats',
            name='biggest_win',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slotstats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slotgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slotstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='slotgame',
            index=models.Index(fields=['user', 'created_at'], name='slots_slotg_user_id_f46829_idx'),
        ),
    ]
