# Generated by Django 5.2.8 on 2026-01-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_alter_slotstats_options_slotstats_biggest_win_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotstats',
            name='biggest_win',
        ),
        migrations.AddField(
            model_name='slotgame',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='slotstats',
            name='highest_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='slotstats',
            name='winning_spins',
            field=models.IntegerField(default=0),
        ),
    ]
