# Generated by Django 5.2.8 on 2025-12-15 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('fortune_mouse', 'Fortune Mouse'), ('fortune_tiger', 'Fortune Tiger'), ('fortune_rabbit', 'Fortune Rabbit')], max_length=32, unique=True)),
                ('target_rtp', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('0.30'))])),
                ('win_prob_cap', models.DecimalField(decimal_places=2, default=Decimal('0.28'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('0.30'))])),
                ('max_steps', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('max_multiplier', models.DecimalField(decimal_places=4, default=Decimal('50.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))])),
                ('base_safe_prob', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.05')), django.core.validators.MaxValueValidator(Decimal('0.99'))])),
                ('safe_prob_decay', models.DecimalField(decimal_places=3, default=Decimal('0.020'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('0.200'))])),
                ('min_safe_prob', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('0.50'))])),
                ('daily_win_cap_per_user', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.CharField(db_index=True, max_length=32)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('cashed_out', 'Cashed Out'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('survival_prob', models.DecimalField(decimal_places=12, default=Decimal('1.0'), max_digits=18)),
                ('current_multiplier', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=18)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_client_msg_id', models.UUIDField(blank=True, null=True)),
                ('server_nonce', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('server_seed_hash', models.CharField(db_index=True, max_length=128)),
                ('server_seed', models.CharField(max_length=128)),
                ('client_seed', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step', models.PositiveIntegerField()),
                ('client_action', models.CharField(max_length=32)),
                ('client_choice', models.CharField(default='', max_length=64)),
                ('safe_prob', models.DecimalField(decimal_places=4, max_digits=6)),
                ('result', models.CharField(choices=[('safe', 'Safe'), ('trap', 'Trap')], max_length=8)),
                ('rng_u', models.DecimalField(decimal_places=12, max_digits=18)),
                ('multiplier_after', models.DecimalField(decimal_places=8, max_digits=18)),
                ('survival_prob_after', models.DecimalField(decimal_places=12, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='fortune.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameOutcome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('house_edge', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rtp_used', models.DecimalField(decimal_places=4, max_digits=6)),
                ('win', models.BooleanField(default=False)),
                ('gross_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reason', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='fortune.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bet', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('suspicious_score', models.PositiveIntegerField(default=0)),
                ('fastest_step_ms', models.PositiveIntegerField(default=999999)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fortune_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'game', 'status'], name='fortune_gam_user_id_4161aa_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['created_at'], name='fortune_gam_created_f035c2_idx'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['session', 'step'], name='fortune_gam_session_cccc7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameround',
            unique_together={('session', 'step')},
        ),
    ]
