# Generated by Django 5.2.8 on 2025-12-26 23:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_remove_gamesession_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtpconfig',
            name='target_rtp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('0.49'))]),
        ),
        migrations.AlterField(
            model_name='rtpconfig',
            name='win_prob_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.28'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('0.48'))]),
        ),
    ]
