# Generated by Django 5.2.8 on 2025-12-29 16:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_alter_rtpconfig_target_rtp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoutcome',
            name='max_multiplier_reached',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='gameoutcome',
            name='special_effects_triggered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gameoutcome',
            name='tiles_picked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='effect_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='multiplier_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Multiplier change for this round', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='tile_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='base_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.00'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='multiplier_history',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of multiplier changes for enhanced games'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='tiles_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON array of tile data for enhanced games'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='enhanced_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='enhanced_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='special_tiles_hit',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='tiles_picked_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rtpconfig',
            name='base_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.45'), max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='rtpconfig',
            name='tile_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='JSON distribution of tile types for enhanced games'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='result',
            field=models.CharField(choices=[('safe', 'Safe'), ('trap', 'Trap'), ('enhanced', 'Enhanced')], max_length=16),
        ),
        migrations.AlterField(
            model_name='rtpconfig',
            name='game',
            field=models.CharField(choices=[('fortune_mouse', 'Fortune Mouse'), ('fortune_tiger', 'Fortune Tiger'), ('fortune_rabbit', 'Fortune Rabbit'), ('fortune_mouse_enhanced', 'Fortune Mouse Enhanced')], max_length=32, unique=True),
        ),
    ]
