# Generated by Django 5.2.8 on 2025-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0004_gameoutcome_max_multiplier_reached_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameoutcome',
            name='max_multiplier_reached',
        ),
        migrations.RemoveField(
            model_name='gameoutcome',
            name='special_effects_triggered',
        ),
        migrations.RemoveField(
            model_name='gameoutcome',
            name='tiles_picked',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='effect_type',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='multiplier_change',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='tile_type',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='base_multiplier',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='multiplier_history',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='tiles_data',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='enhanced_sessions',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='enhanced_wins',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='special_tiles_hit',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='tiles_picked_total',
        ),
        migrations.RemoveField(
            model_name='rtpconfig',
            name='base_multiplier',
        ),
        migrations.RemoveField(
            model_name='rtpconfig',
            name='tile_distribution',
        ),
        migrations.AlterField(
            model_name='gameround',
            name='result',
            field=models.CharField(choices=[('safe', 'Safe'), ('trap', 'Trap')], max_length=8),
        ),
        migrations.AlterField(
            model_name='rtpconfig',
            name='game',
            field=models.CharField(choices=[('fortune_mouse', 'Fortune Mouse'), ('fortune_tiger', 'Fortune Tiger'), ('fortune_rabbit', 'Fortune Rabbit')], max_length=32, unique=True),
        ),
    ]
