# Generated by Django 5.2.8 on 2025-12-31 08:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0005_remove_gameoutcome_max_multiplier_reached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='client_action',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='multiplier_after',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='result',
            field=models.CharField(choices=[('safe', 'Safe'), ('trap', 'Trap')], default='safe', max_length=8),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='rng_u',
            field=models.DecimalField(decimal_places=12, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='safe_prob',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.55'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='survival_prob_after',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.0'), max_digits=18),
        ),
    ]
