# Generated by Django 5.2.8 on 2025-12-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0006_alter_gameround_client_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
