# Generated by Django 5.2.8 on 2025-12-31 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0007_gamesession_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['id', 'user_id'], name='fortune_gam_id_e94619_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['server_nonce'], name='fortune_gam_server__dbe9f3_idx'),
        ),
    ]
