# Generated by Django 5.2.8 on 2025-12-30 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberheist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cyberheist',
            name='hack_success_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cyberheist',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='failed_heists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='total_hacks_successful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='traced_heists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='cyberheist',
            index=models.Index(fields=['user', 'created_at'], name='heist_cyber_user_id_e38d35_idx'),
        ),
        migrations.AddIndex(
            model_name='cyberheist',
            index=models.Index(fields=['win_ratio'], name='heist_cyber_win_rat_e471c4_idx'),
        ),
    ]
