# Generated by Django 5.2.8 on 2025-12-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heist', '0002_alter_cyberheist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heiststats',
            name='failed_heists',
        ),
        migrations.RemoveField(
            model_name='heiststats',
            name='total_hacks_successful',
        ),
        migrations.RemoveField(
            model_name='heiststats',
            name='traced_heists',
        ),
        migrations.AddField(
            model_name='heiststats',
            name='highest_hack_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
