# Generated by Django 5.2.8 on 2025-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heist', '0003_remove_heiststats_failed_heists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyberheist',
            name='hack_success_rate',
        ),
        migrations.RemoveField(
            model_name='heiststats',
            name='highest_hack_rate',
        ),
        migrations.AddField(
            model_name='heiststats',
            name='epic_heists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='large_heists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='legendary_heists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='medium_heists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heiststats',
            name='small_heists',
            field=models.IntegerField(default=0),
        ),
    ]
