# Generated by Django 5.2.8 on 2025-12-30 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorswitch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorswitchgame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='colorswitchgame',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='colorswitchstats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='colorswitchgame',
            index=models.Index(fields=['user', 'created_at'], name='colorswitch_user_id_dfbf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='colorswitchgame',
            index=models.Index(fields=['status'], name='colorswitch_status_37c2ec_idx'),
        ),
    ]
