# Generated by Django 5.2.8 on 2025-11-29 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotionBrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients_used', models.JSONField()),
                ('potion_result', models.JSONField()),
                ('success_level', models.CharField(max_length=20)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PotionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_brews', models.IntegerField(default=0)),
                ('perfect_brews', models.IntegerField(default=0)),
                ('good_brews', models.IntegerField(default=0)),
                ('failed_brews', models.IntegerField(default=0)),
                ('total_won', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bet', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('legendary_ingredients_used', models.IntegerField(default=0)),
                ('highest_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preferred_ingredient_matches', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
