# Generated by Django 5.2.8 on 2025-12-30 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potionbrew',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='potionbrew',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='potionstats',
            name='divine_brews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='potionstats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='potionstats',
            name='legendary_brews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='potionstats',
            name='masterpiece_brews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='potionbrew',
            index=models.Index(fields=['user', 'created_at'], name='potion_poti_user_id_6f4e04_idx'),
        ),
        migrations.AddIndex(
            model_name='potionbrew',
            index=models.Index(fields=['win_ratio'], name='potion_poti_win_rat_b6e78c_idx'),
        ),
    ]
