# Generated by Django 5.2.8 on 2025-12-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgame',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='grid_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='status',
            field=models.CharField(choices=[('playing', 'playing'), ('failed', 'failed'), ('completed', 'completed')], default='playing', max_length=20),
        ),
    ]
