# Generated by Django 5.2.8 on 2025-12-30 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardgame_attempts_alter_cardgame_grid_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardgame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cardgame',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardstats',
            name='highest_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cardstats',
            name='highest_win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='cardgame',
            index=models.Index(fields=['user', 'created_at'], name='cards_cardg_user_id_d55ade_idx'),
        ),
        migrations.AddIndex(
            model_name='cardgame',
            index=models.Index(fields=['status'], name='cards_cardg_status_c62296_idx'),
        ),
    ]
