# Generated by Django 5.2.8 on 2025-12-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='demo_balance',
            new_name='spot_balance',
        ),
    ]
