# Generated by Django 5.2.8 on 2026-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='first_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
