# Generated by Django 4.2.27 on 2026-03-19 06:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0005_unmatchedwebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('daily_deposit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total deposits allowed per day for this bank account', max_digits=18, null=True)),
                ('monthly_deposit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total deposits allowed per month for this bank account', max_digits=18, null=True)),
                ('min_deposit_amount', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum amount per deposit for this bank account', max_digits=18)),
                ('max_deposit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount per deposit for this bank account', max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default bank account to show users')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='DepositLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('min_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_bank_name', models.CharField(blank=True, max_length=100)),
                ('source_account_number', models.CharField(blank=True, max_length=30)),
                ('source_account_name', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Reference from payment gateway/bank', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='deposit_proofs/%Y/%m/%d/')),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='wallets_wit_user_id_dfd6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['reference'], name='wallets_wit_referen_c7d20b_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['created_at'], name='wallets_wit_created_195af7_idx'),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='admin_bank',
            field=models.ForeignKey(help_text='Admin bank account that user is paying into', on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='wallets.adminbank'),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositlimit',
            name='admin_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_limits', to='wallets.adminbank'),
        ),
        migrations.AddField(
            model_name='depositlimit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminbank',
            index=models.Index(fields=['is_active', 'is_default'], name='wallets_adm_is_acti_7f1143_idx'),
        ),
        migrations.AddIndex(
            model_name='adminbank',
            index=models.Index(fields=['account_number'], name='wallets_adm_account_1d9ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['user', 'status'], name='wallets_dep_user_id_b40eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['reference'], name='wallets_dep_referen_746d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['transaction_reference'], name='wallets_dep_transac_1bfa81_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['created_at'], name='wallets_dep_created_baf177_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['status', 'expires_at'], name='wallets_dep_status_8b6f40_idx'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['admin_bank', 'status'], name='wallets_dep_admin_b_28bdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='depositlimit',
            index=models.Index(fields=['user', 'is_active'], name='wallets_dep_user_id_41661e_idx'),
        ),
        migrations.AddIndex(
            model_name='depositlimit',
            index=models.Index(fields=['admin_bank', 'is_active'], name='wallets_dep_admin_b_32a87b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depositlimit',
            unique_together={('user', 'period', 'admin_bank')},
        ),
    ]
